---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Pre-req - Fetch volumes
      ansible.builtin.include_tasks: ../__fetch_volumes.yml
      vars:
        post_op: false

    - name: Performing operation on the iDRAC device using default
            reset_type with invalid hostname
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "randomHostname"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        reset_config: true
      ignore_errors: true
      ignore_unreachable: true
      register: idrac_storage_controller_idrac_storage_controller_tmp

    - name: "Verifying operation on the iDRAC device using default
              reset_type with invalid hostname"
      ansible.builtin.assert:
        that:
          - '"<urlopen error Unable to communicate with iDRAC randomHostname."
              in reset_config_out.msg or
              "<urlopen error [Errno -2] Name or service not known>" in
              reset_config_out.msg'

    - name: Performing operation on the iDRAC device using default
            reset_type with invalid username
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "WrongUsername123"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        reset_config: true
        controller_id: "{{ controller_name }}"
      ignore_errors: true
      ignore_unreachable: true
      register: idrac_storage_controller_idrac_storage_controller_tmp

    - name: "Verifying operation on the iDRAC device using default
              reset_type with invalid username"
      ansible.builtin.assert:
        that:
          - '"HTTP Error 401" in reset_config_out.msg'

    - name: Performing operation on the iDRAC device using default
            reset_type with invalid password
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "WrongPassword@123"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        reset_config: true
      ignore_errors: true
      ignore_unreachable: true
      register: idrac_storage_controller_idrac_storage_controller_tmp

    - name: "Verifying operation on the iDRAC device using default
              reset_type with invalid password"
      ansible.builtin.assert:
        that:
          - '"HTTP Error 401" in reset_config_out.msg'

    - name: Performing operation on the iDRAC device using default
            reset_type without controller ID
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: None
        reset_config: true
      ignore_errors: true
      ignore_unreachable: true
      register: idrac_storage_controller_tmp

    - name: "Verifying operation on the iDRAC device using default
              reset_type without controller ID"
      ansible.builtin.assert:
        that:
          - reset_config_out.msg == "controller_id with id 'None'
            not found in system"

    - name: Playbook to set controller attributes with Job wait by providing
            a invalid value for attribute
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        attributes:
          CopybackMode: "On"
          EnhancedAutoImportForeignConfigurationMode: "invalid value"
          PatrolReadMode: Disabled
        apply_time: Immediate
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying set controller attributes with Job wait by providing
            a invalid value for attribute
      ansible.builtin.assert:
        that:
          - attributes_config_out.msg == "Unable to configure the controller
            attribute(s) settings."
          - attributes_config_out.failed

    - name: Playbook to set controller attributes with Job wait by providing
            a invalid apply_time
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        attributes:
          CopybackMode: "On"
          PatrolReadMode: Disabled
        apply_time: "Invalid_apply_tine"
        maintenance_window:
          start_time: "2026-09-14T06:59:35-05:00"
          duration: "180"
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying disk status change to online in Normal
       mode (invalid apply_time)
      ansible.builtin.assert:
        that:
          - "attributes_config_out.msg == 'value of apply_time must be one
            of: Immediate, OnReset, AtMaintenanceWindowStart,
            InMaintenanceWindowOnReset, got: Invalid_apply_tine'"
          - attributes_config_out.failed

    - name: Playbook to set controller attributes with Job wait when
            "apply_time=AtMaintenanceWindowStart"  by providing a invalid
            maintenance_window
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        attributes:
          CopybackMode: "On"
          PatrolReadMode: Disabled
        apply_time: "AtMaintenanceWindowStart"
        maintenance_window:
          start_time: "Invalid_start_time"
          duration: "180"
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying disk status change to online in Normal
       mode (invalid start time)
      ansible.builtin.assert:
        that:
          - "'The start time should be in the format
           YYYY-MM-DDThh:mm:ss<offset>' in attributes_config_out.msg"
          - attributes_config_out.failed

    - name: Create a list of dictionaries of dictionaries
      ansible.builtin.set_fact:
        vol_details:
          id: "Invalid"
          expand_capacity_disk: 362785

    - name: Playbook to expand size of disk by target with Job wait
            with "volume_id " as Invalid value
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        command: OnlineCapacityExpansion
        controller_id: "{{ controller_name }}"
        volumes: "{{ vol_details }}"
        job_wait: true
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying disk status change to online in Normal
       mode (invalid virtual disk)
      ansible.builtin.assert:
        that:
          - "oce_vd_out.msg == 'Unable to locate the virtual disk with
            the ID: Invalid'"
          - oce_vd_out.failed

    - name: Update the value of the id key
      ansible.builtin.set_fact:
        vol_details: "{{ vol_details | combine({'id': physicaldisks[0],
                      'expand_capacity_disk': -1}) }}"

    - name: Playbook to expand size of disk by target with Job wait with
            "volume_id" and Invalid expand_capacity_disk
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        command: OnlineCapacityExpansion
        controller_id: "{{ controller_name }}"
        volumes: "{{ vol_details }}"
        job_wait: true
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying size expansion of disk by target with Job wait with
            "volume_id" and Invalid expand_capacity_disk
      ansible.builtin.assert:
        that:
          - oce_vd_out.failed

    - name: Create a list of dictionaries of dictionaries.
      ansible.builtin.set_fact:
        disk_details:
          status: "online"

    - name: Playbook to change disk status when target is missing
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        disks: "{{ disk_details }}"
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Update the value of the id key.
      ansible.builtin.set_fact:
        disk_details: "{{ disk_details | combine({'id': 'Invalid'}) }}"

    - name: Playbook to change disk status when target Id is invalid
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        disks: "{{ disk_details }}"
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying change disk status when target Id is invalid
      ansible.builtin.assert:
        that:
          - "'Unable to locate the physical disk with the ID: Invalid'
            in pd_state_out.msg"
          - pd_state_out.failed

    - name: Create a dictionary for dedicated hotspare
      ansible.builtin.set_fact:
        volume_details:
          id: "{{ physicaldisks[0] }}"
          dedicated_hot_spare: "Invalid"

    - name: Playbook with invalid assign dedicated hot spare
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        controller_id: "{{ controller_name }}"
        volumes: "{{ volume_details }}"
      ignore_errors: true
      register: idrac_storage_controller_tmp

    - name: Verifying - Invalid assign dedicated hot spare
      ansible.builtin.assert:
        that:
          - "'Unable to locate the physical disk with the ID: Invalid'
            in assign_dedicated_spare_out.msg"
          - assign_dedicated_spare_out.failed
