---
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    cleanup: cleanup.yml
scenario:
  test_sequence:
    - create
    - prepare
    - prepare
    - converge
    - cleanup
    - destroy
