---
- name: Ansible Module for HTTP Firmware Update with Job Tracking
  hosts: redfish_hosts
  gather_facts: false
  connection: local
  vars:
    firmware_image_uri: "{{ http_firmware_uri | default('http://192.168.0.1/firmware_repo/component.exe') }}"

  tasks:
    - name: Include firmware job tracking
      ansible.builtin.include_tasks: redfish_firmware_jobtracking.yml
