---
- name: Ansible Module for Local Firmware Update with Job Tracking
  hosts: redfish_hosts
  gather_facts: false
  connection: local
  vars:
    firmware_image_uri: "{{ local_firmware_path | default('/home/firmware_repo/component.exe') }}"

  tasks:
    - name: Include firmware job tracking
      ansible.builtin.include_tasks: redfish_firmware_jobtracking.yml
