---
- name: Ansible Module for Simple Firmware Update
  hosts: redfish_hosts
  gather_facts: false
  connection: local

  tasks:
    - name: Update the firmware from a single executable file available in a local path
      dellemc.openmanage.redfish_firmware:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        image_uri: "{{ local_firmware_path }}"
      register: firmware_result
      tags:
        - local-update

    - name: Update the firmware from a single executable file available in a HTTP protocol
      dellemc.openmanage.redfish_firmware:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        image_uri: "{{ http_firmware_uri }}"
      register: firmware_result
      tags:
        - http-update
