---
- name: Redfish Storage Volume Create with Job Tracking
  hosts: redfish_hosts
  gather_facts: false
  connection: local
  vars:
    volume_state: present
    volume_name: "{{ volume_name | default('VD_BOSS') }}"
    controller_id: "{{ controller_id | default('AHCI.Slot.6-1') }}"
    drives:
      - Disk.Direct.1-1:AHCI.Slot.6-1
      - Disk.Direct.0-0:AHCI.Slot.6-1
    volume_type: "{{ volume_type | default('Mirrored') }}"
    optimum_io_size_bytes: "{{ optimum_io_size_bytes | default(65536) }}"

  tasks:
    - name: Include storage volume job tracking
      ansible.builtin.include_tasks: redfish_storage_volume_jobtracking.yml
