---
- name: Prepare system for Molecule tests
  hosts: all
  become: true
  tasks:
    - name: "Pre-requisites"
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/molecule/resources/tests/downgrade.yml"
