---
- name: Configure Server Power Setting
  hosts: redfish_hosts
  gather_facts: false
  connection: local

  tasks:
    - name: Manage power state of the first device.
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        reset_type: "On"
      register: power_result
      tags: power-on

    - name: Manage power state of a specified device.
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        reset_type: "ForceOff"
        resource_id: "System.Embedded.1"
      register: power_result
      tags: power-off

    - name: Perform AC Power Cycle with final power state On
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        oem_reset_type:
          dell:
            final_power_state: "On"
            reset_type: "PowerCycle"
      register: power_result
      tags: power-cycle-on

    - name: Perform AC Power Cycle with final power state Off
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        oem_reset_type:
          dell:
            final_power_state: "Off"
            reset_type: "PowerCycle"
      register: power_result
      tags: power-cycle-off
