---
- name: Configure Redfish subscriptions
  hosts: redfish_hosts
  gather_facts: false
  connection: local

  tasks:
    - name: Add Redfish metric subscription
      dellemc.openmanage.redfish_event_subscription:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        destination: "{{ subscription_destination | default(omit) }}"
        event_type: MetricReport
        event_format_type: MetricReport
        state: present
      register: metric_subscription_result
      tags: add_metric_subscription

    - name: Add Redfish alert subscription
      dellemc.openmanage.redfish_event_subscription:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        destination: "{{ subscription_destination | default(omit) }}"
        event_type: Alert
        event_format_type: Event
        state: present
      register: alert_subscription_result
      tags: add_alert_subscription

    - name: Delete Redfish subscription with a specified destination
      dellemc.openmanage.redfish_event_subscription:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ca_path: "{{ ca_path | default(omit) }}"
        destination: "{{ subscription_destination | default(omit) }}"
        state: absent
      register: delete_subscription_result
      tags: delete_subscription
