---
- name: Fetch firmware version
  ansible.builtin.uri:
    url: "https://{{ lookup('env', 'IDRAC_IP') | ansible.utils.ipwrap }}:443\
      /redfish/v1/UpdateService/Oem/Dell/DellSoftwareInventory"
    user: "{{ lookup('env', 'IDRAC_USER') }}"
    password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
    method: GET
    force_basic_auth: true
    validate_certs: false
    body_format: json
    return_content: true
    status_code: 200
  register: uri_data
  ignore_errors: true
  check_mode: false

- name: Set legacy iDRAC flag
  ansible.builtin.set_fact:
    cacheable: true
    is_legacy_idrac: true

- name: Set legacy iDRAC flag
  ansible.builtin.set_fact:
    cacheable: true
    is_legacy_idrac: false
  when: uri_data.status == 200
